INSERT INTO PRODUCT (ID, PRODUCT_AVAILABLE, BRAND, CATEGORY, DESCRIPTION, NAME, PRICE, STOCK_QUANTITY, RELEASE_DATE)
VALUES (1, TRUE, 'Samsung', 'Electronics', 'Flagship Android smartphone', 'Galaxy S24', 899.99, 50, '2024-01-17');

INSERT INTO PRODUCT (ID, PRODUCT_AVAILABLE, BRAND, CATEGORY, DESCRIPTION, NAME, PRICE, STOCK_QUANTITY, RELEASE_DATE)
VALUES (2, TRUE, 'Apple', 'Electronics', 'Latest iPhone model', 'iPhone 15 Pro', 1199.99, 35, '2023-09-22');

INSERT INTO PRODUCT (ID, PRODUCT_AVAILABLE, BRAND, CATEGORY, DESCRIPTION, NAME, PRICE, STOCK_QUANTITY, RELEASE_DATE)
VALUES (3, TRUE, 'Dell', 'Computers', 'Business laptop with Intel i7', 'Latitude 7440', 1499.99, 20, '2024-03-10');

INSERT INTO PRODUCT (ID, PRODUCT_AVAILABLE, BRAND, CATEGORY, DESCRIPTION, NAME, PRICE, STOCK_QUANTITY, RELEASE_DATE)
VALUES (4, FALSE, 'Sony', 'Electronics', 'Noise cancelling headphones', 'WH-1000XM5', 349.99, 0, '2022-05-12');

INSERT INTO PRODUCT (ID, PRODUCT_AVAILABLE, BRAND, CATEGORY, DESCRIPTION, NAME, PRICE, STOCK_QUANTITY, RELEASE_DATE)
VALUES (5, TRUE, 'Nike', 'Fashion', 'Running shoes for men', 'Air Zoom Pegasus', 129.99, 75, '2024-02-01');

INSERT INTO PRODUCT (ID, PRODUCT_AVAILABLE, BRAND, CATEGORY, DESCRIPTION, NAME, PRICE, STOCK_QUANTITY, RELEASE_DATE)
VALUES (6, TRUE, 'Adidas', 'Fashion', 'Comfortable sports shoes', 'Ultraboost 24', 179.99, 40, '2024-01-20');

INSERT INTO PRODUCT (ID, PRODUCT_AVAILABLE, BRAND, CATEGORY, DESCRIPTION, NAME, PRICE, STOCK_QUANTITY, RELEASE_DATE)
VALUES (7, TRUE, 'LG', 'Home Appliances', 'Double door refrigerator', 'SmartCool 450L', 799.99, 15, '2023-11-15');

INSERT INTO PRODUCT (ID, PRODUCT_AVAILABLE, BRAND, CATEGORY, DESCRIPTION, NAME, PRICE, STOCK_QUANTITY, RELEASE_DATE)
VALUES (8, TRUE, 'HP', 'Computers', 'Gaming laptop', 'Omen 16', 1699.99, 10, '2024-04-05');

INSERT INTO PRODUCT (ID, PRODUCT_AVAILABLE, BRAND, CATEGORY, DESCRIPTION, NAME, PRICE, STOCK_QUANTITY, RELEASE_DATE)
VALUES (9, FALSE, 'Boat', 'Accessories', 'Wireless earbuds', 'Airdopes 141', 49.99, 0, '2023-08-11');

INSERT INTO PRODUCT (ID, PRODUCT_AVAILABLE, BRAND, CATEGORY, DESCRIPTION, NAME, PRICE, STOCK_QUANTITY, RELEASE_DATE)
VALUES (10, TRUE, 'Canon', 'Electronics', 'Mirrorless camera', 'EOS R50', 899.99, 12, '2023-02-08');

ALTER TABLE PRODUCT ALTER COLUMN ID RESTART WITH 11;